django_china/apps/coolsites/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('',
                       url(r'^$', 'coolsites.views.index', name='sites_index'),
                       url(r'^create/$', 'coolsites.views.create', name='sites_create'),

)

django_china/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
                       # url(r'^admin/', include(admin.site.urls)),
                       url(r'^comments/', include('django.contrib.comments.urls')),
)

urlpatterns += patterns('',
                        url(r'^accounts/', include('profiles.urls')),
                        url(r'^$', include('homepage.urls')),
                        url(r'^sites/', include('coolsites.urls')),
                        url(r'^wiki/', include('markupwiki.urls')),
                        url(r'^topics/', include('topics.urls')),
                        url(r'^people/', include('people.urls')),

)
media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')
urlpatterns += patterns('',
                        (r'^%s/(?P<path>.*)$' % media_url, 'django.views.static.serve',
                         {
                             'document_root': settings.MEDIA_ROOT,
                             }),
                        )

django_china/apps/coolsites/models.py
# -*- coding: utf-8 -*-

from django.db import models

from django.contrib.auth.models import User

class SiteCategory(models.Model):
    name = models.CharField(u'分类名', max_length=24, unique=True)
    creater = models.ForeignKey(User)

    class Meta:
        ordering = ['id']

    def __unicode__(self):
        return self.name

class CoolSites(models.Model):
    name = models.CharField(u'网站名', max_length=64, unique=True)
    site = models.URLField(u'网址', unique=True)
    category = models.ForeignKey(SiteCategory)
    about = models.TextField(u'网站简介', null=True, blank=True)
    creater = models.ForeignKey(User)
    pub_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['id']

    def __unicode__(self):
        return '%s: %s' % (self.name, self.site)

django_china/apps/coolsites/forms.py
from django import forms
from django.contrib.auth.models import User

from coolsites.models import SiteCategory, CoolSites

class SiteCategoryForm(forms.ModelForm):
    class Meta:
        model = SiteCategory

    def save(self, user):
        model, created = SiteCategory.objects.get_or_create(
            name = self.cleaned_data['name'],
            creater = user)

        if created:
            model.save()

        return model

class CoolSitesForm(forms.ModelForm):
    class Meta:
        model = CoolSites
        fields = ('name', 'site', 'category', 'about', )

    def save(self, user):
        model, created = CoolSites.objects.get_or_create(
            name = self.cleaned_data['name'],
            site = self.cleaned_data['site'],
            category = self.cleaned_data['category'],
            about = self.cleaned_data['about'],
            creater = user
            )

        if created:
            model.save()

        return model

django_china/apps/coolsites/views.py
# -*- coding: utf-8 -*-

from django.http import HttpResponseRedirect, Http404, HttpResponseForbidden, HttpResponse
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse

from django.contrib.auth.models import User

from coolsites.models import SiteCategory, CoolSites
from coolsites.forms import SiteCategoryForm, CoolSitesForm

def index(request):
    """酷站首页面"""
    sc = SiteCategory.objects.all() ## site分类

    return render_to_response('coolsites/index.html',
                              {'sc': sc},
                              context_instance=RequestContext(request))

@login_required
def create(request):
    """登录用户可自行添加相关网站"""

    if request.method == 'POST':
        form = CoolSitesForm(request.POST)
        if form.is_valid():
            model = form.save(request.user)
            return HttpResponseRedirect(reverse('sites_index'))
    else:
        form = CoolSitesForm()

    return render_to_response('coolsites/create.html',
                              {'form': form},
                              context_instance=RequestContext(request))

django_china/templates/coolsites/create.html
{% extends "coolsites/base.html" %}

{% block content_title %}添加新网站{% endblock %}

{% block main %}

<div class="container_12" id="main">
  <div class="grid_12">
    <form action="" method="post">
      {{ form.as_p }}
      <button type="submit">添加新站</button>
    </form>
  </div>
</div>


{% endblock %}

django_china/templates/coolsites/index.html
{% extends "coolsites/base.html" %}

{% block title %}Django 酷站{% endblock %}

{% block content_title %}<a href="{% url sites_index %}">Django 酷站</a>{% endblock %}

{% block main %}

<div class="container_12" id="main">
  <div class="grid_12">
    如果你所知道的基于Django开发的网站不在下面的列表中，请你<a href="{% url sites_create %}" title="需要登录才能进行操作">添加</a>上。
  </div>
</div>

{% if sc %}
{% for c in sc %}
<div class="container_12" id="main">
  <div class="grid_12">
    <div class="site-fl">{{ c.name|safe }}</div>
    <div class="site-nr">
    {% if c.coolsites_set.all %}
      <ul>
        {% for site in c.coolsites_set.all %}
        <li><a href="{{ site.site|safe }}" title="{{ site.about|linebreaksbr }}" target="_blank">{{ site.name|safe }}</a></li>
        {% endfor %}
      </ul>
    {% else %} 本分类暂时无相关网站 {% endif %}
    </div>
    </div>

  </div>
</div>
{% endfor %}
{% else %}
  <p>暂无分类<p>
{% endif %}

{% endblock %}